import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
    try {
        const authHeader = req.headers.get('authorization');
        if (!authHeader) {
            return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
        }

        const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
        const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

        const supabase = createClient(supabaseUrl, supabaseAnonKey, {
            global: {
                headers: {
                    Authorization: authHeader,
                },
            },
        });

        const { data: { user }, error: userError } = await supabase.auth.getUser();
        if (userError || !user) {
            return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
        }

        const body = await req.json();
        const {
            type = 'income',
            raw_transcript,
            amount_usd,
            platform_fee_usd = 0,
            withdrawal_fee_usd = 0,
            exchange_rate,
            category,
            ...dynamicFields
        } = body;

        // Ensure user profile exists
        const { data: profile, error: profileSelectError } = await supabase
            .from('profiles')
            .select('id')
            .eq('id', user.id)
            .single();

        if (!profile) {
            await supabase.from('profiles').upsert({
                id: user.id,
                email: user.email,
            }, { onConflict: 'id' });
        }

        // Construct dynamic insertion object to accommodate new currencies 
        // generated by the AI block (e.g. amount_inr, net_inr)
        const zeroDecimalCurrencies = ['PKR', 'INR', 'JPY', 'KRW', 'IDR', 'VND'];

        let final_transcript = raw_transcript;

        // Enforce integer saving for zero-decimal original currencies
        if (dynamicFields.original_currency && dynamicFields.original_amount !== undefined) {
            if (zeroDecimalCurrencies.includes(dynamicFields.original_currency.toUpperCase())) {
                dynamicFields.original_amount = Math.round(Number(dynamicFields.original_amount));
            }
            final_transcript = (raw_transcript || '') + `|META:${JSON.stringify({ c: dynamicFields.original_currency, a: dynamicFields.original_amount })}`;
        }

        // Apply strict integer rounding to targeted zero-decimal DB columns as well
        Object.keys(dynamicFields).forEach(key => {
            if (key.startsWith('amount_') || key.startsWith('net_')) {
                const currencyCode = key.split('_')[1]?.toUpperCase();
                if (currencyCode && zeroDecimalCurrencies.includes(currencyCode)) {
                    dynamicFields[key] = Math.round(Number(dynamicFields[key]));
                }
            }
        });

        const insertData: any = {
            user_id: user.id,
            type,
            raw_transcript: final_transcript,
            amount_usd,
            platform_fee_usd,
            withdrawal_fee_usd,
            exchange_rate,
            category,
        };

        // Pass any dynamic fields (like amount_pkr, net_pkr) straight to DB
        // Do NOT pass original_ fields because the DB column doesn't exist yet! We encode it in raw_transcript.
        Object.keys(dynamicFields).forEach(key => {
            if (key.startsWith('amount_') || key.startsWith('net_')) {
                insertData[key] = dynamicFields[key];
            }
        });

        const { data, error } = await supabase.from('transactions').insert(insertData).select().single();

        if (error) {
            console.error('Transaction save error:', error);
            return NextResponse.json({ error: error.message }, { status: 500 });
        }

        return NextResponse.json({ success: true, transaction: data });
    } catch (error: any) {
        console.error('Transaction API error:', error);
        return NextResponse.json({ error: error?.message || 'Server error' }, { status: 500 });
    }
}
